# Branch Protection Configuration for Solo Development
# This file documents the branch protection rules for this repository
# These need to be configured in GitHub repository settings (one-time setup)

master:
  required_status_checks:
    strict: true
    contexts:
      - "lint"
      - "molecule"
  
  required_pull_request_reviews:
    required_approving_review_count: 0  # No review required for solo dev
    dismiss_stale_reviews: false
    require_code_owner_reviews: false
  
  enforce_admins: false  # Allow admin (you) to bypass if needed
  
  restrictions: null  # No push restrictions
  
  required_conversation_resolution: false  # Not needed for solo dev

# Solo Developer Workflow:
# 1. Create feature branch from master: `git checkout -b feature/my-feature`
# 2. Make changes and push to feature branch: `git push origin feature/my-feature`
# 3. Create Pull Request to master
# 4. Wait for "lint" and "Molecule Default Test" to pass (required)
# 5. No review approval needed - you can merge your own PR
# 6. Merge PR after pipelines succeed
# 7. Delete feature branch

# GitHub CLI setup command (run once):
# gh api repos/ginanck/role_base/branches/master/protection \
#   --method PUT \
#   --field required_status_checks='{"strict":true,"contexts":["lint","Molecule Default Test"]}' \
#   --field enforce_admins=false \
#   --field required_pull_request_reviews='{"required_approving_review_count":0}' \
#   --field restrictions=null
