---
# tasks file for role_tomcat

- name: create tomcat group
  ansible.builtin.group:
    name: "{{ tomcat_group }}"
    state: present

- name: create tomcat user
  ansible.builtin.user:
    name: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    home: "/home/tomcat"
    shell: /bin/bash
    create_home: true
    state: present

- name: check current download URL status
  ansible.builtin.uri:
    url: "{{ tomcat_download_current_url }}"
    method: HEAD
    timeout: 10
    return_content: false
    status_code: [200, 404]
  ignore_errors: true
  register: tomcat_current_url_check

- name: check archive download URL status
  ansible.builtin.uri:
    url: "{{ tomcat_download_archive_url }}"
    method: HEAD
    timeout: 10
    return_content: false
    status_code: [200, 404]
  ignore_errors: true
  register: tomcat_archive_url_check
  when: tomcat_current_url_check.status != 200

- name: set download url and availability facts
  ansible.builtin.set_fact:
    tomcat_download_url: >-
      {%- if tomcat_current_url_check.status == 200 -%}
        {{ tomcat_download_current_url }}
      {%- elif tomcat_archive_url_check.status == 200 -%}
        {{ tomcat_download_archive_url }}
      {%- else -%}
        ""
      {%- endif -%}
    tomcat_download_available: >-
      {{ tomcat_current_url_check.status == 200 or tomcat_archive_url_check.status == 200 }}

- name: create tomcat versioned directory
  ansible.builtin.file:
    path: "{{ tomcat_versioned_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0744'
  when: 
    - tomcat_download_available | bool
    - tomcat_download_url != ""

- name: download and extract tomcat
  ansible.builtin.unarchive:
    src: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_versioned_dir }}"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0744'
    remote_src: yes
    extra_opts: [--strip-components=1]
  register: tomcat_unarchive
  when: 
    - tomcat_download_available | bool
    - tomcat_download_url != ""

- name: check folder is exists
  ansible.builtin.stat:
    path: "{{ tomcat_versioned_dir }}"
  register: tomcat_versioned_dir_exists

- name: create/update symbolic link to active Tomcat version
  ansible.builtin.file:
    src: "{{ tomcat_versioned_dir }}"
    dest: "{{ tomcat_home_link_dir }}"
    state: link
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    force: yes
  when: tomcat_versioned_dir_exists.stat.exists

- name: get default java path
  ansible.builtin.stat:
    path: /bin/java
  register: java_file_stats

- name: set java home path
  ansible.builtin.set_fact:
    default_java_home_path: "{{ java_file_stats.stat.lnk_source | dirname | dirname }}"

- name: create tomcat service file
  ansible.builtin.template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
    owner: root
    group: root
    mode: 0644

- name: create setenv.sh
  ansible.builtin.template:
    src: setenv.sh.j2
    dest: "{{ tomcat_versioned_dir }}/bin/setenv.sh"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: 0644

- name: create tomcat users and roles
  ansible.builtin.template:
    src: tomcat-users.xml.j2
    dest: "{{ tomcat_versioned_dir }}/conf/tomcat-users.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0744'

- name: configure manager/META-INF/context.xml
  ansible.builtin.template:
    src: manager.meta.context.xml.j2
    dest: "{{ tomcat_versioned_dir }}/webapps/manager/META-INF/context.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0744'

- name: configure host-manager/META-INF/context.xml
  ansible.builtin.template:
    src: host-manager.meta.context.xml.j2
    dest: "{{ tomcat_versioned_dir }}/webapps/host-manager/META-INF/context.xml"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'

- name: Remove existing ROOT.war if present
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ tomcat_root_path }}"
    - "{{ tomcat_root_link_path }}"
  loop_control:
    label: "{{ item }}"

- name: create link for webapp to ROOT.war
  ansible.builtin.file:
    src: "{{ tomcat_webapp_path }}"
    dest: "{{ tomcat_root_link_path }}"
    state: link
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    follow: false
    force: yes

- name: create tomcat log directory
  ansible.builtin.file:
    path: "{{ tomcat_log_dir }}"
    state: directory
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'

- name: create log dir symbolic link
  ansible.builtin.file:
    src: "{{ tomcat_log_dir }}"
    dest: "{{ tomcat_log_link_path }}"
    state: link
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    force: yes

- name: restart tomcat service
  ansible.builtin.systemd_service:
    state: restarted
    name: tomcat
    daemon_reload: true
    enabled: true
