---
dependency:
  name: shell
  command: |
    ansible-galaxy role install -r meta/install_requirements.yml -p ./roles --force
    ansible-galaxy collection install -r meta/install_requirements.yml -p ./collections --force
driver:
  name: docker
platforms:
  - name: role-tomcat-ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
      - /run/lock
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles:../../../
    ANSIBLE_COLLECTIONS_PATHS: ../../collections
  inventory:
    host_vars:
      role-tomcat-ubuntu2404:
        ansible_user: root
  playbooks:
    converge: ../resources/converge.yml
    prepare: ../resources/prepare.yml
verifier:
  name: ansible
  options:
    playbook: ../resources/verify.yml
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
